name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: true
      - name: make init
        run: make init
      - name: make check
        run: make check
